### ISSUE TITLE
The Toaster cannot handle teams notification.

### ISSUE THREAD

**Issue by linitfor** [JxBP/Toaster#1]
The Toaster cannot handle some notification such as, Teams.

**Comment by JxBP** [comment]
Thanks for the report. It looks like I forgot to mention it in the README but currently only native toasts are supported. Teams creates its own notification Window.

I'll try and make Toaster work for those notifications specifically too. In the meantime you could [configure Teams to use the native notification system](https://support.microsoft.com/en-us/office/change-your-notifications-style-in-microsoft-teams-0da93820-93d0-4da3-86b6-fc28d19908e3).

**Comment by JxBP** [comment]
I released a version v1.0.2 with the requested feature. You can download a precompiled executable from the releases page.
