### ISSUE TITLE
Microsoft New teams notification is not support 

### ISSUE THREAD

**Issue by linitfor** [JxBP/Toaster#3]
As title. the new teams version. 23320.3021.2567.4799 
cannot support to let the notification change position.

**Comment by linitfor** [comment]
I have capture the New teams notification window

Can the author help to update ?

![圖片](https://github.com/JxBP/Toaster/assets/58168507/6e300b6c-7032-4dc3-8761-861696f05bf4)

**Comment by JxBP** [comment]
I would like to fix this but unfortunately don't have that Teams Version for testing. If you could help me test/debug Team's notification windows a bit more I might be able to find a solution though.
Would it be possible to get in contact on a more instant-message like platform than Github?
My preferred platform would be Matrix (@jxbp:matrix.falconmc.org) but Discord is also fine by me.

**Comment by linitfor** [comment]
I have try the Matrix. But I am not familiar Matrix app. I have message you. Can you see my words.?
If you can't, you can help to find me. Or we can discuss on Discord message.
![圖片](https://github.com/JxBP/Toaster/assets/58168507/5c234a84-e53b-445b-9999-1060fdf225cd)

**Comment by linitfor** [comment]
https://answers.microsoft.com/en-us/msteams/forum/all/how-can-i-fix-the-notification-banner-position-for/fb5a24e4-69c2-4d55-b05f-113e593d57bc?page=1

It seem a bug from Teams. May member have complain to MS.
