### ISSUE TITLE
The toaster configuration window cannot correctly hide to system tray

### ISSUE THREAD

**Issue by linitfor** [JxBP/Toaster#4]
I have put the toaster.exe in auto start on boot. 

But I have found the app have the probability which cannot minimize to system tray.

The app window will show on the desktop like the following snapshot.

![圖片](https://github.com/JxBP/Toaster/assets/58168507/9b781d1b-2126-4c7e-8966-61462720a524)

**BTW, Can you help to enhancement the app to support auto start on system boot ?**

**Comment by JxBP** [comment]
This seems to be an issue with Windows's autostart feature as I can't even close the Window normally without opening the "real window" using the tray icon. I'm unfortunately not very knowledgable about Windows so I'm not sure how I could solve this.
I know this is a silly idea but maybe you could try and make an AutoHotKey script that closes it? 🫤

**Comment by linitfor** [comment]
It seem not encounter every time on system boot. These two days I have not happened again until now.

**Comment by JxBP** [comment]
What is odd to me is that the Window has different controls (like the red cross) at the top compared to normal windows and can't be closed normally.
I have unfortunately don't know why it's some sort of special window when ran as startup app and how I would fix this.
